# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Parse activity samples from a GT3X file
#'
#' @param filename (char*) path to a log.bin file inside the unzipped gt3x folder, which contains the activity samples
#' @param max_samples Maximum number of rows to parse. The returned matrix will always contain this number of rows, having zeroes if
#' not data is found.
#' @param scale factor Scale factor for the activity samples.
#' @param verbose Print the parameters from the log.bin file and other messages?
#' @param debug Print information for every activity second
#'
#' @return
#' Returns a matrix with max_samples rows and 4 columns, where the first 3 columns are the acceleration samples and
#' the last column is timestamps in seconds (including 100th of seconds) starting from 00:00:00 1970-01-01 UTC (UNIX time)
#'
parseGT3X <- function(filename, max_samples, scale_factor, sample_rate, verbose = FALSE, debug = FALSE) {
    .Call('_read_gt3x_parseGT3X', PACKAGE = 'read.gt3x', filename, max_samples, scale_factor, sample_rate, verbose, debug)
}

